language: cpp

compiler:
  - clang++

matrix:
  include:
    - os: linux
      # addons:
      #   apt:
      #     packages:
      #       # - llvm-6.0
      #       # - llvm-6.0-dev
      #       # - clang-6.0
      #       # - clang-6.0-dev
      #       # - libclang-6.0
      #       # - libclang-6.0-dev
      #     sources:
      #       - llvm-toolchain-trusty-6.0
      #       - sourceline: 'ppa:ubuntu-toolchain-r/test'
      #     update: true
      env:
        - MATRIX_EVAL="export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`llvm-config --libdir`"
    - os: osx
      env:
        - MATRIX_EVAL="export HOMEBREW_NO_AUTO_UPDATE=1 ; brew install llvm ; brew link --force --overwrite llvm"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -H. -Bbuild -DCMAKE_VERBOSE_MAKEFILE=ON
  - cmake --build build

